nasdaq_dict = {
    'Apple Inc': 'AAPL', 'Microsoft Corp': 'MSFT', 'Amazon.com Inc': 'AMZN', 'NVIDIA Corp': 'NVDA',
    'Meta Platforms Inc': 'META', 'Broadcom Inc': 'AVGO', 'Alphabet Inc (Class A)': 'GOOGL',
    'Alphabet Inc (Class C)': 'GOOG', 'Tesla Inc': 'TSLA', 'Adobe Inc': 'ADBE', 'Costco Wholesale Corp': 'COST',
    'PepsiCo Inc': 'PEP', 'Advanced Micro Devices Inc': 'AMD', 'Netflix Inc': 'NFLX', 'Cisco Systems Inc': 'CSCO',
    'T-Mobile US Inc': 'TMUS', 'Intel Corp': 'INTC', 'Comcast Corp': 'CMCSA', 'Intuit Inc': 'INTU', 'QUALCOMM Inc': 'QCOM',
    'Amgen Inc': 'AMGN', 'Texas Instruments Inc': 'TXN', 'Honeywell International Inc': 'HON',
    'Applied Materials Inc': 'AMAT', 'Booking Holdings Inc': 'BKNG', 'Starbucks Corp': 'SBUX',
    'Intuitive Surgical Inc': 'ISRG', 'Gilead Sciences Inc': 'GILD', 'Mondelez International Inc': 'MDLZ',
    'Automatic Data Processing Inc': 'ADP', 'Lam Research Corp': 'LRCX', 'Analog Devices Inc': 'ADI',
    'Palo Alto Networks Inc': 'PANW', 'PDD Holdings Inc ADR': 'PDD', 'Vertex Pharmaceuticals Inc': 'VRTX',
    'Regeneron Pharmaceuticals Inc': 'REGN', 'Micron Technology Inc': 'MU', 'Synopsys Inc': 'SNPS',
    'MercadoLibre Inc': 'MELI', 'KLA Corp': 'KLAC', 'Cadence Design Systems Inc': 'CDNS', 'CSX Corp': 'CSX',
    'PayPal Holdings Inc': 'PYPL', 'Marriott International Inc/MD': 'MAR', 'ASML Holding NV': 'ASML',
    'Airbnb Inc': 'ABNB', 'Lululemon Athletica Inc': 'LULU', "O'Reilly Automotive Inc": 'ORLY',
    'Workday Inc': 'WDAY', 'Monster Beverage Corp': 'MNST', 'Cintas Corp': 'CTAS', 'NXP Semiconductors NV': 'NXPI',
    'Charter Communications Inc': 'CHTR', 'CrowdStrike Holdings Inc': 'CRWD', 'PACCAR Inc': 'PCAR',
    'Autodesk Inc': 'ADSK', 'Microchip Technology Inc': 'MCHP', 'Marvell Technology Inc': 'MRVL', 'Dexcom Inc': 'DXCM',
    'Copart Inc': 'CPRT', 'Ross Stores Inc': 'ROST', 'Keurig Dr Pepper Inc': 'KDP', 'Paychex Inc': 'PAYX',
    'Kraft Heinz Co/The': 'KHC', 'IDEXX Laboratories Inc': 'IDXX', 'Seagen Inc': 'SGEN',
    'American Electric Power Co Inc': 'AEP', 'Fortinet Inc': 'FTNT', 'Old Dominion Freight Line Inc': 'ODFL',
    'Exelon Corp': 'EXC', 'Electronic Arts Inc': 'EA', 'AstraZeneca PLC ADR': 'AZN', 'Constellation Energy Corp': 'CEG',
    'Fastenal Co': 'FAST', 'Cognizant Technology Solutions Corp': 'CTSH', 'Biogen Inc': 'BIIB', 'Datadog Inc': 'DDOG',
    'Verisk Analytics Inc': 'VRSK', 'CoStar Group Inc': 'CSGP', 'Xcel Energy Inc': 'XEL',
    'ON Semiconductor Corp': 'ON', 'Baker Hughes Co': 'BKR', 'Trade Desk Inc/The': 'TTD',
    'GE HealthCare Technologies Inc': 'GEHC', 'Moderna Inc': 'MRNA', 'Atlassian Corp': 'TEAM', 'Zscaler Inc': 'ZS',
    'GLOBALFOUNDRIES Inc': 'GFS', 'Warner Bros Discovery Inc': 'WBD', 'Dollar Tree Inc': 'DLTR',
    'Diamondback Energy Inc': 'FANG', 'ANSYS Inc': 'ANSS', 'eBay Inc': 'EBAY',
    'Walgreens Boots Alliance Inc': 'WBA', 'Zoom Video Communications Inc': 'ZM', 'Illumina Inc': 'ILMN',
    'Sirius XM Holdings Inc': 'SIRI', 'Align Technology Inc': 'ALGN', 'Enphase Energy Inc': 'ENPH',
    'JD.com Inc ADR': 'JD', 'Lucid Group Inc': 'LCID'
}

